# Generated by Django 5.2.2 on 2025-06-08 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deploy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_repo_url', models.URLField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('up', 'Up'), ('down', 'Down')], default='in_progress', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deploy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='deployments.deploy')),
            ],
            options={
                'unique_together': {('deploy', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('deploy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='deployments.deploy')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='deployments.provider')),
            ],
        ),
    ]
